upstream ticketing_app {

    least_conn;

    server  app:8080  weight=1  max_fails=3  fail_timeout=30s;

    # Keep-alive pool to upstream
    keepalive 32;

    # Keep-alive tuning
    keepalive_requests  1000;    # max requests on one keep-alive upstream conn
    keepalive_timeout   60s;     # idle keep-alive conn lifetime
}
